# .github/actions/send-junit-to-api/action.yml
name: Send JUNIT XML Files to Evergreen API
description: Sends JUNIT XML files to the Evergreen API.

# Definice pro znovupoužití workflow
on:
  workflow_call:
    inputs:
      subproject:
        required: false
        type: string
        description: 'Sub project name'

# Definice kroků v rámci composite action
runs:
  using: "composite"
  steps:
    - name: Send JUNIT XML Files to Evergreen API
      shell: bash
      run: |
        echo "Workflow Run ID: ${{ github.run_id }}"

        # Define the base URL
        if [ "${{ contains(runner.labels, 'self-hosted') }}" == "true" ]; then
          base_url="http://evergreen.ihmc.us"
        else
          base_url="https://evergreen.ihmc.us"
        fi
        
        cd repository-group/${{ github.event.repository.name }}/${{ inputs.subproject }}/src/test/build/test-results/test/
        for file in TEST-*.xml; do
          if [ -f "$file" ]; then
            echo "Sending $file to API"
            curl -X POST \
              -H "WorkflowRunID: ${{ github.run_id }}" \
              -F "file=@$file" \
              "$base_url/api/junitupload.php"
          else
            echo "No XML files found matching TEST-*.xml"
          fi
        done
