name: Gradle test (fast)

on:
  workflow_dispatch

permissions:
  checks: write
  contents: read

jobs:
  atlas:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
    with:
      subproject: 'atlas'
      test-category: 'fast'
  
