name: Gradle test (fast) experimental

on:
  workflow_dispatch

permissions:
  checks: write
  contents: read

jobs:
  atlas:
    uses: langer-jaroslav/ihmc-open-robotics-software/.github/workflows/gradle-test.yml@develop
    with:
      subproject: 'ihmc-robotics-toolkit'
      test-category: 'fast'
      requires-self-hosted: true  
