name: Gradle test (fast)

on:
  workflow_dispatch

permissions:
  checks: write
  contents: read

jobs:
  atlas:
    uses: .github/workflows/gradle-test.yml@develop
    with:
      subproject: 'ihmc-robotics-toolkit'
      test-category: 'fast'
      requires-self-hosted: true  
