name: Test

on:
  workflow_dispatch

jobs:
  build-deploy:
    runs-on: self-hosted
      
    steps:
    - uses: actions/checkout@v4   

    - name: docker test
      run: docker run hello-world
      
    - name: Send JUNIT XML Files to Evergreen API
      uses: ./.github/actions/send-junit-to-api
      if: success() || failure() # always run even if the previous step fails
      with:
        subproject: ${{ inputs.subproject }}
