name: Test

on:
  workflow_dispatch

jobs:
  build-deploy:
    runs-on: self-hosted
      
    steps:
    - name: My first step - check out repository
      uses: actions/checkout@v4 

    - name: Send JUNIT XML Files to Evergreen API
      uses: ./.github/actions/send-junit-to-api
      if: success() || failure() # always run even if the previous step fails
      with:
        subproject: 'TEST'
